### ISSUE TITLE
Embedding model + RecursiveUrlLoader

### ISSUE THREAD

**Issue by itsnotmik** [DrAlzahraniProjects/csusb_fall2024_cse6550_team1#109]
@smrchanda877 @acraig07 @Jagadeesh-ajjada 

Please give the `RecursiveURL-soup` branch a test

I converted our `MiniLM-L12` embedding model to `MiniLM-L6`. L6 is the second fastest embedding model on `sentence-transformers` doing 14600 sentences a second.

The initialization on my laptop still takes over 20 minutes. (I am unsure how long it takes as it hasn't finished yet)

Please let me know how long it takes for the initialization process to finish

**Comment by smrchanda877** [comment]
It took me about 30-35 minutes for the total initialization process
Creating the vector store with the embeddings takes the most amount of time (31 minutes)

**Comment by ACraig7** [comment]
It took me about 15 minutes. It probably didnt help that I am building a Image on my VM so i can set up the Juypter Notebook the way the professor specified in my Q&A post from today.
