### ISSUE TITLE
Confusion Matrix

### ISSUE THREAD

**Issue by smrchanda877** [DrAlzahraniProjects/csusb_fall2024_cse6550_team1#128]

**Comment by smrchanda877** [comment]
This has some information about how we can implement confusion matrix: 

https://chatgpt.com/share/67218a6f-89a8-800d-a109-a76f76eb690b

**Comment by ACraig7** [comment]
I just noticed something in the QA from his inital post about the confusion matrix. He says this : 
`Confusion Matrix Display: Show a live confusion matrix with six key metrics—Sensitivity, Specificity, Accuracy, Precision, Recall, and F1 Score—displayed below it. Include a reset button beneath the metrics to clear all tests, allowing users to start over as needed. Users should be able to use thumbs up and down icons to provide feedback after each answer.`

That last line says: **Users should be able to use thumbs up and down icons to provide feedback after each answer**. So to me that means we are using user feedback to determine to determine TP, TN, FP,  and FN. Now the next thing we need to figure out is the whole answerable and unanswerable question part. It seems like we pre determine the questions from this: 
`Question Preparation: Prepare an SQA document with 10 answerable questions and 10 unanswerable questions.`

There is a few ways we could do this. Have a menu that has the SQA document questions that the user can select a pre determined question and it asks the chatbot that question and we know ahead of time if the question is answerable or unanswerable and we give it a TP, TN, FP, FN rating based on user input. Another way is that we compare each question asked  to the 10 unanswerable and 10 answerable question in the backend and if it matches we assign it a TP, TN, FP, FN rating based on user feedback.

Let me know what you think

**Comment by smrchanda877** [comment]
I think comparing user questions with the ground truth is the way to go. Also, ground truth needs to have way more than 10 questions for it to function the way we want.
Also, there are some clustering techniques we can use to get started with setting up ground truth. We can, based on thumbs up and thumbs down, adjust the ground truth down the line.
I think he wants SQA with 10 answerable and 10 unanswerable questions to test our projects accuracy probably

**Comment by ACraig7** [comment]
I see what you mean but i dont think he wants it to be that complicated. I think he wants the confusion matrix to only work with the SQA document questions which means we dont have to do the ground truth stuff. I will ask him in the Q&A.

**Comment by ACraig7** [comment]
@smrchanda877 So, the professor responded. It seems as if I was on the right path. I asked him this: 

`Do you want the confusion matrix to only interact with the SQA document questions? To further explain, the user feedback, thumbs up or thumbs down, should only affect the confusion matrix if the question asked was apart of the SQA document questions. So, if I ask the chatbot a question that is not apart of the SQA document questions the thumbs up or thumbs down does nothing to the confusion matrix. Please let me know if this is what you want from the confusion matrix.`

and he responded with this: 

`Yes, the confusion matrix interacts only with the questions in the SQA document.`

So, it seems that is not as complicated as we were thinking.

**Comment by smrchanda877** [comment]
Oh, that's great. Thanks for asking. Now, we can just to focus on creating a good SQA document
