### ISSUE TITLE
Update embedding to Mini L12

### ISSUE THREAD

**Issue by itsnotmik** [DrAlzahraniProjects/csusb_fall2024_cse6550_team1#142]

**Comment by itsnotmik** [comment]
Contact @itsnotmik if help is needed

Change our embedding model from `L6` to `L12` in the RAG file. We want to be using `all-MiniLM-L12-v2`.

After embedding model has been changed. Please regenerate the `.db` files by deleting any included `.db` files and running the docker. It will take ~20 minutes to do the embedding process.

Once the new `.db` files are created using the embedding function L12, download the `.db` files from the docker. Put the new files in the folder

Push the changes to include the new `.db` files into Dev

**Comment by ACraig7** [comment]
Updated the embedding model to `L12` and added new `.db` files see pull request #166. Awaiting review.

**Comment by ACraig7** [comment]
Complete
