### ISSUE TITLE
Remove NeMo guardrails

### ISSUE THREAD

**Issue by itsnotmik** [DrAlzahraniProjects/csusb_fall2024_cse6550_team1#144]

**Comment by itsnotmik** [comment]
Contact @itsnotmik @ACraig7 if help is needed

Implement NeMo guardrails using information provide [LINK](https://docs.nvidia.com/nemo/guardrails/getting_started/5_output_rails/README.html)

Specifically we want to implement rails on the Output from the LLM. Input can be implemented in the future if time permits

**Comment by vamsikrishnabandaru3** [comment]
should we also make the rules to implement NeMo guardrails.

**Comment by itsnotmik** [comment]
Since Triton is a dependency of NeMo guardrails and Triton currently fails to build from source on several different systems we are removing this

@adinasurya1 Since you were working on the Triton work. Feel free to remove NeMo from the Dockerfile to get some credit for the Triton work you did (even if its just a little credit)
