### ISSUE TITLE
TODO: Mamba Functionality

### ISSUE THREAD

**Issue by itsnotmik** [DrAlzahraniProjects/csusb_fall2024_cse6550_team1#4]
Current implementation uses python + pip to install requirements. Must be change to full Mamba implementation

1) Implement MAMBA installation through either .YML, .TXT, or by listing required libraries in dockerfile
2) Set up dockerfile commands to set the environment for mamba + ensure app can run through mamba environment
     - Sources for possible methods
         - https://stackoverflow.com/questions/55123637/activate-conda-environment-in-docker
         - https://stackoverflow.com/questions/76215066/how-to-make-docker-container-automatically-activate-a-conda-environment
         - https://micromamba-docker.readthedocs.io/en/latest/quick_start.html

**Comment by ACraig7** [comment]
Added Mamba and enviroment.yml for libraries. Not all libraries are in Mamba. environment.yml for mamba libraries and requirements.txt for other non mamba libraries

**Comment by itsnotmik** [comment]
The current implementation seems to not be the version that Dr. Alzahrani wants and seems to error out when creating the environment. The version he links to is installed through Miniforge available at https://github.com/conda-forge/miniforge.

I attempted to follow the instructions that were available through the GitHub link but it was not installing correct as I frequently received a bash/sh error 127 (Command not found). 

@ACraig7 can you look through the link above and see if you are able to get this installation method working?

**Comment by ACraig7** [comment]
@itsnotmik What error are you getting exactly? Also, are you sure we are suppose to be using that version of miniforge cause on the github page they say it is deprecated and that you should switch to miniforge3. If we want to use miniforge3 we can do that.

**Comment by itsnotmik** [comment]
That github page should be the Miniforge3 installation page

I followed the installation instructions on that GitHub and errored out at the 'conda activate' or 'source conda/etc/profile.d/conda.sh' step. Anytime I tried to use the commands I got error code 127. Which is the error code for command not found. I even tried to set conda as the path but was unable to work. If you follow the instructions and replace our current install of conda you should reach the same error. I can send you the code I was trying, but it might be best for you to try those instructions and see if it works for you.

**Comment by ACraig7** [comment]
I updated the dockerfile to use the miniforge from the github link you provided, it is in a branch called Miniforge. Also, it works perfectly fine for me.  Let me know if it all good for you.

**Comment by itsnotmik** [comment]
I was attempting to download by manually putting in Linux and Architecture instead of using the prebuilt -uname links. It works on my system now and made a few adjustments which can be found in the Miniforge branch

**Comment by ACraig7** [comment]
Issue resolved.
