### ISSUE TITLE
Jupyter Notebook (Anyone can Work on it).

### ISSUE THREAD

**Issue by ACraig7** [DrAlzahraniProjects/csusb_fall2024_cse6550_team1#63]
Needs the jupyter notebook completed for hello world.

**Comment by Jagadeesh-ajjada** [comment]
HI Ritvik I appreciate that you taken this task, I believe he is the one working on this as of now, and update you states here in discussion until we got the access to create the task dashboard. Have any doubts also you can ask here.

**Comment by ritvik180** [comment]
![image](https://github.com/user-attachments/assets/27632a2b-3855-4886-b493-555aa8dd1ffd)
If you need any changes let me know

**Comment by itsnotmik** [comment]
Awesome, approved the pull request you submitted.

@Boganabi do we need the HELLO WORLD code documented or our current code?

**Comment by Boganabi** [comment]
Everything should be documented. As you write code other people (or you) should be documenting it.

**Comment by Jenildabhi5103** [comment]
@ritvik180  If you need any help in Jupyter notebook than ask me
