### ISSUE TITLE
Which project board do we want?

### ISSUE THREAD

**Issue by itsnotmik** [DrAlzahraniProjects/csusb_fall2024_cse6550_team1#69]
@Jagadeesh-ajjada @Boganabi @acraig07

Dr. Alzahrani wants us to select a project type. I am thinking we should select the Template called `Team Planning`

Do you also agree with this selection?

**Comment by itsnotmik** [comment]
it includes the task board and these extra tabs that may be useful for our planning

![image](https://github.com/user-attachments/assets/77ca5db5-9b5d-4532-bd02-43bed6fd5948)

**Comment by Jagadeesh-ajjada** [comment]
Am thinking Board is better
![image](https://github.com/user-attachments/assets/739582e1-d5e7-4f42-98c9-a910eca118b9)

**Comment by itsnotmik** [comment]
Submitted the request for a blank board to Dr. Alzahrani. Thank you
