### ISSUE TITLE
Project Task Board Not Visible

### ISSUE THREAD

**Issue by itsnotmik** [DrAlzahraniProjects/csusb_fall2024_cse6550_team1#77]
@Boganabi 

Dr. Alzahrani stated he added the project board to our repo, but I am unable to see in it the projects.

Can you check to see if it has been added and you can enable it for us?

**Comment by Boganabi** [comment]
I am able to see it, but I have to invite everyone to the project in order for everyone to be able to see it. A little inconvenient, but I'll be inviting everyone today, so look out for that.

**Comment by Boganabi** [comment]
Invite sent to everyone, please accept as soon as you can :)
