### ISSUE TITLE
Request for a call regarding Task Assignment

### ISSUE THREAD

**Issue by Jagadeesh-ajjada** [DrAlzahraniProjects/csusb_fall2024_cse6550_team1#78]
Since we’ve initiated the project template, I request @Boganabi to schedule a call tomorrow so we can discuss and assign tasks equally. This way, we can involve the remaining four team members in the contribution, rather than selecting tasks individually. I believe we should have the call after Tuesday's class. Any suggestions are welcome!.

**Comment by 008784796** [comment]
sound's good

**Comment by Boganabi** [comment]
Unfortunately, I am not available for a call tomorrow, but you are free to meet on your own accord at any time.
If you would like my input on the assigned tasks, you can leave a note on those tasks and I will take a look at them as soon as I can.

**Comment by Jagadeesh-ajjada** [comment]
This is what the conflict I told we have Jupyter documentation and SRS documentation with out assign it to anyone those are in In-progress state who know who is working on that in this way i don't think so it will work.
