### ISSUE TITLE
Out of Memory Issue from Dr. Alzahrani

### ISSUE THREAD

**Issue by itsnotmik** [DrAlzahraniProjects/csusb_fall2024_cse6550_team1#8]
Running on Windows 10:

ERROR [7/9] RUN mamba env create -f /app/environment.yml                                                                                                         39.5s

[7/9] RUN mamba env create -f /app/environment.yml:
0.664 Channels:
0.664  - conda-forge
0.664 Platform: linux-64
0.664 Collecting package metadata (repodata.json): ...working... done
15.27 Solving environment: ...working... Killed

Dockerfile:34

  32 |
  33 |     # Create a Conda environment using Mamba and install Python packages from environment.yml
  34 | >>> RUN mamba env create -f /app/environment.yml
  35 |
  36 |     # Activate the environment for subsequent commands

ERROR: failed to solve: process "/bin/sh -c mamba env create -f /app/environment.yml" did not complete successfully: exit code: 137

### Unable to replicate on my laptop with 8GB of memory

Might be able to fix this issue by removing ubuntu:latest and implementing either python or mambaforge docker image

**Comment by ACraig7** [comment]
I changed Ubuntu to python in the minforge branch yesterday. I forgot to do a merge request yesterday. Doing that right now,

**Comment by ACraig7** [comment]
Added "-slim" to python version. This does not contain the Debian packages that the default version has. Had no issues running it. Documentation related to -slim https://hub.docker.com/_/python

**Comment by itsnotmik** [comment]
Through further research exit code 137 refers to any docker exit that was killed with SIGKILL. This can be related to OOM, out of storage space, but not necessarily only these.

Currently my docker is using the WSL 2 backend, so my resources are entirely managed by windows but it seems that no matter the build my memory usage is maxed out during the docker build cycle. Docker ends up using ~3.5GB of memory on my system and is able to complete the build. So OOM should not be an issue unless the functionality is different when using the Hyper-V backend.

My suspicion is that the 137 error here is related to storage space as with our requirements the docker image is ~20GB. When removing the requirements it decreases our docker image to < 10GB. Unfortunately, I have been unable to replicate this error as my build just hangs when storage space is full instead of erroring with SIGKILL. I propose that we remove the necessary requirements until they are needed, leaving essentially only StreamLit and its dependencies. This will also allow us to ask Dr. Alzahrani to test the code again on the light weight version to see if the error still occurs.

Removing the unused requirements also has the benefit of decreasing build time. The requirements install takes 900 seconds or 15 minutes on my system when using ~3.5GB of memory. This may not be as big of time save on other systems but can allow use to work/build faster until those requirements are needed

I have pushed the code and made a merge request on the matter. Please review when available.

**Comment by itsnotmik** [comment]
Dr. Alzahrani suggested that we all test run the DOCKERFILE to reduce the chance for failure on his system. I am requesting that everyone who hasn't had a chance to participate on the project this week to help by completing this work. @Adenkri45 @BandaruDinesh @smrchanda877 @veeruadina @Dinesh0614 @Jagadeesh-ajjada @Jenildabhi5103 @tejaswi-142 @ritvik180 @vamsikrishnabandaru3 

Please follow the instructions in the README file to download, build and run the DOCKERFILE on your own system. Then reply to this issue thread with the following information in the following format. If you have an error please post the error message.

**Operating System:** 
**Build Successful:** 
**Error Message:** 
**Accessible through Localhost port 5001:** 
**Issues with installation, etc:** 
**Screenshot of Hello World:** 

For example, my post would be this:

**Operating System:** Windows 10
**Build Successful:** Yes
**Error Message:** N/A
**Accessible through localhost port 5001:** Yes
**Issues with installation, docker, etc:** No
**Screenshot of Hello World:** 
![image](https://github.com/user-attachments/assets/586e3b59-cc3a-4de7-a54b-9cbe90ff3efd)

**Comment by veeruadina** [comment]
It worked in mine. Should I post it on GitHub ? If yes, in discussions ryt?

**Comment by itsnotmik** [comment]
@veeruadina please post it here, thank you

**Comment by 008784796** [comment]
Operating System:Windows 10
Build Successful:Yes
Error Message:N/A
Accessible through Localhost port 5001:Yes
Issues with installation, etc:No
Screenshot of Hello World:
![Screenshot 2024-09-12 132156](https://github.com/user-attachments/assets/c94157b8-9872-4f15-a129-ab22fa3c68a2)

**Comment by smrchanda877** [comment]
Operating System:Windows 11
Build Successful:Yes
Error Message:N/A
Accessible through Localhost port 5001:Yes
Issues with installation, etc:No
Screenshot of Hello World:
![image](https://github.com/user-attachments/assets/a2c101c6-300d-49c8-bc83-6d3add52d399)

**Comment by vamsikrishnabandaru3** [comment]
Operating System: MAC
Build Successful:Yes
Error Message:N/A
Accessible through Localhost port 5001:Yes
Issues with installation, etc:No
Screenshot of Hello World:

<img width="1440" alt="Screenshot 2024-09-12 at 6 06 56 PM" src="https://github.com/user-attachments/assets/6b7b686c-0d07-4f2e-9532-a508726cfee2">

**Comment by BandaruDinesh** [comment]
Operating System: Mac OS
Build Successful: Yes
Error Message: N/A
Accessible through localhost port 5001: Yes
Issues with installation, docker, etc: No
<img width="1470" alt="Screenshot 2024-09-12 at 6 07 14 PM" src="https://github.com/user-attachments/assets/c3fc449d-b136-46a0-8999-a70e8325acc1">

**Comment by Dinesh0614** [comment]
Operating System: windows 11 Home 
Processor: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz   2.80 GHz
Build Successful: Yes
Error Message: N/A
Accessible through Localhost port 5001: Yes
Issues with installation, etc: No
Screenshot of Hello World:
![Screenshot 2024-09-12 175808](https://github.com/user-attachments/assets/a04d38e3-6835-4fa0-98d2-8e242a33c7de)

**Comment by ritvik180** [comment]
Operating System: Windows 11
Build Successful:Yes
Error Message:N/A
Accessible through Localhost port 5001:Yes
Issues with installation, etc:No
Screenshot of Hello World:
![image](https://github.com/user-attachments/assets/2ae03398-7919-4fea-b9e8-2e9f69191256)

**Comment by ACraig7** [comment]
@itsnotmik Tried something different to fix this issue. The error seems to be a memory issues as you stated. So I made the dockerfile install in two stages. This is in the multi stage branch. Tested fine for me. Let me know if you have issues.

**Comment by ACraig7** [comment]
Operating System: Linux (Ubuntu 24.04.1)
Build Successful: Yes
Error Message: N/A
Accessible through Localhost port 5001:Yes
Issues with installation, etc: No
Screenshot of Hello World:
![image](https://github.com/user-attachments/assets/d5b46439-599d-47bf-b7a8-a877e0d1dfaa)

**Comment by itsnotmik** [comment]
> @itsnotmik Tried something different to fix this issue. The error seems to be a memory issues as you stated. So I made the dockerfile install in two stages. This is in the multi stage branch. Tested fine for me. Let me know if you have issues.

Dr. Alzahrani posted on our Team1 discussion his attempt to run the code on MacOS again. From what it looks like he is attempting to clone HELLO-WORLD branch and not the main branch. I am setting a merge request onto that branch to make it match the main currently

Also I will look over the code in the morning and ensure that it runs on my system as well

**Comment by ACraig7** [comment]
@itsnotmik that is interesting cause the git command in the readme is for the main branch.

**Comment by Adenkri45** [comment]
Operating System: Windows 11
Build Successful: Yes
Error Message: N/A
Accessible through Localhost port 5001:Yes
Issues with installation, etc.: No
Screenshot of Hello World:
![Docker Run Image](https://github.com/user-attachments/assets/d812b326-a1b0-47f5-b96f-7f92cb6a72bc)

**Comment by ACraig7** [comment]
@itsnotmik Just created a new branch called MacOSfix that may fix this specific issue. The branch is works for me on windows 10.

**Comment by tejaswi-142** [comment]
Operating System: Windows 11
Build Successful: Yes
Error Message: N/A
Accessible through Localhost port 5001:Yes
Issues with installation, etc.: No
Screenshot of Hello World:
![image](https://github.com/user-attachments/assets/ad9818c6-19fc-48ee-9ec3-9eb007d6f1f9)

**Comment by itsnotmik** [comment]
Error is no longer posted by Dr. Alzahrani in the discussion board
