### ISSUE TITLE
Jupyter intergration with Apache

### ISSUE THREAD

**Issue by ACraig7** [DrAlzahraniProjects/csusb_fall2024_cse6550_team1#83]
Set up Jupyter so that it can run on Apache.

**Comment by ACraig7** [comment]
Jupyter is now running along side Apache in the `Apache-Jupyter-Test` branch.
Made changes to dockerfile so that Jupyter does not require a password to access, can change this in the future.
Changes to Dockerfile
- Re-exposed port 6001 for Juypter
- Created Juypter config and disabled authentication
```
# Jupyter Notebook port
EXPOSE 6001

# Create a Jupyter config file to disable token authentication
RUN jupyter notebook --generate-config && \
    echo "c.NotebookApp.token = ''" >> /root/.jupyter/jupyter_notebook_config.py && \
    echo "c.NotebookApp.password = ''" >> /root/.jupyter/jupyter_notebook_config.py && \
    echo "c.NotebookApp.ip = '0.0.0.0'" >> /root/.jupyter/jupyter_notebook_config.py && \
    echo "c.NotebookApp.port = 6001" >> /root/.jupyter/jupyter_notebook_config.py && \
    echo "c.NotebookApp.open_browser = False" >> /root/.jupyter/jupyter_notebook_config.py

```

Updated README.md
- Added New URL's to access Juypter notebook
- Updated Docker run command to open port 6001
```
You can access the Jupyter Notebook at:

http://localhost:6001/ or http://127.0.0.1:6001/
```
`docker run -d -p 5001:5001 -p 6001:6001 team1_app`

Screenshots of Juypter running on Linux VM with custom domain:
![image](https://github.com/user-attachments/assets/053c6641-1415-43f8-8ecb-e77e8d70fc9b)

Extra screenshots of Juypter running on different URL's on Linux VM:
![image](https://github.com/user-attachments/assets/9298a0d5-cb23-49c2-9c94-0d952da72128)
![image](https://github.com/user-attachments/assets/51cfbd9f-97b8-4a67-a474-789fea738134)

**Comment by ACraig7** [comment]
@itsnotmik @Jagadeesh-ajjada If you guys have time can you test the `Apache-Jupyter-Test` branch and make sure you have no issues. I had some free time and got Jupyter running alongside Apache on my VM. I do not want to merge anything till we have conformation that our code is running on the CSUSB servers and that this is the way the professor wants us to implement Jupyter alongside Apache.

**Comment by Jagadeesh-ajjada** [comment]
Yeah sure

**Comment by Jagadeesh-ajjada** [comment]
I have tested the code from the branch Apache-Jupyter-Test. It's working for both 5001 and 6001 servers  without any error on Ubuntu 24.04.1 LTS.

![image](https://github.com/user-attachments/assets/eb4d0223-2767-4da9-a2b8-cab7f40c8c7c)

![image](https://github.com/user-attachments/assets/07683b06-8290-4e96-90a9-91466014eabf)

![image](https://github.com/user-attachments/assets/24e68a96-184f-4b94-9d79-44dec8231971)

**Comment by itsnotmik** [comment]
Tested and working on both links with both StreamLit and Jupyter being accessible

Just waiting to see if it works on CSE server!

**Comment by Boganabi** [comment]
I have received confirmation from Dr. Alzahrani that our base application is working on the CSE server. I suppose our next step is to see if we can get Jupyter working on the server as well, if possible. 

Thank you guys for the amazing work!

**Comment by itsnotmik** [comment]
I am unsure if this would be possible. From my limited understanding of HTTPS and port usage. I believe it is only possible for a single application to be bound to a port. (Maybe I am incorrect about this).

Meaning that we would either need 2 ports or we would need a way to access Jupyter through StreamLit (or vice versa). Jupyter and StreamLit are both full service applications that require a port connection so I am unsure if this is possible. 

I could only find any information on someone using Jupyter to build a StreamLit application. But we specifically need Jupyter to access documentation files (not to build the streamlit)

**Comment by ACraig7** [comment]
Yeah I am not sure but my guess is that he would have to set up the CSE server so we can access another port for juypter. We can ask about it in class and see what he says.

**Comment by ACraig7** [comment]
Complete
