### ISSUE TITLE
Not running on CSE Web Server.

### ISSUE THREAD

**Issue by ACraig7** [DrAlzahraniProjects/csusb_fall2024_cse6550_team1#84]
From Dr. Alzahrani on discussion board:
- Error: Only port 5001 is allowed for use (9/29/2024)

**Comment by ACraig7** [comment]
I think the issue has to do with this line of code in app.py:
`subprocess.run(["jupyter", "notebook", "--ip=0.0.0.0", "--port=6001", "--no-browser", "--allow-root"])`
Going to comment it out and push it to the Apache branch and request merge.

**Comment by itsnotmik** [comment]
I was about to say the same thing. Should be a simple fix until we are allowed to open Jupyter port

**Comment by ACraig7** [comment]
> I was about to say the same thing. Should be a simple fix until we are allowed to open Jupyter port

@itsnotmik I already did the fix and the pull request is awaiting approval.

**Comment by ACraig7** [comment]
Pushed fix in pull request  `Updated app.py for Apache fix #85 `. Merged with main. Awaiting upload to CSE server for testing.

**Comment by ACraig7** [comment]
@itsnotmik So, If i try to run it on Apache with this 000-default.conf file: 
```
<VirtualHost *:80>
        ServerName team1.local
 
        #ServerAdmin webmaster@localhost
        #DocumentRoot /var/www/html
 
        # Proxy to Docker Container running on port 5001
        ProxyPreserveHost On
        ProxyPass /team1 http://localhost:5001/team1
        ProxyPassReverse /team1 http://localhost:5001/team1
 
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
```

You get websocket errors of this: 
```
Firefox can’t establish a connection to the server at ws://team1.local/team1/_stcore/stream. main.33ba0d1c.js:19:42049
 
WebsocketConnection WebSocket onerror main.33ba0d1c.js:10:1392160
```
but if you configure Apache with websocket with this 000-defaul.conf file: 

```
<VirtualHost *:80>
        ServerName team1.local
 
        #ServerAdmin webmaster@localhost
        #DocumentRoot /var/www/html
 
        # Proxy to Docker Container running on port 5001
        ProxyPreserveHost On
        ProxyPass /team1 http://localhost:5001/team1
        ProxyPassReverse /team1 http://localhost:5001/team1
 
        RewriteEngine On
        RewriteCond %{HTTP:Upgrade} =websocket [NC]
        RewriteCond %{HTTP:Connection} upgrade [NC]
        RewriteRule /team1/(.*) ws://localhost:5001/team1/$1 [P,L]
 
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
```

it works fine. I also commented this out of the dockerfile:

```
ENV STREAMLIT_SERVER_BASEURLPATH=/team1
ENV STREAMLIT_SERVER_PORT=5001 

EXPOSE 5001
```
It works fine with the above code commented out on Windows for me and on the VM with the second 000-default.conf file listed. Also Streamlit requires websocket to run, so either he has to get rid of the streamlit requirement or configure the schools servers for it. The current modified code is in the Apache branch and I will create a merge request for it.

**Comment by itsnotmik** [comment]
Working on https://sec.cse.csusb.edu/team1
