### ISSUE TITLE
Low-fidelity & Architecture Design Documentation

### ISSUE THREAD

**Issue by 008445808** [DrAlzahraniProjects/csusb_fall2024_cse6550_team1#86]
### Low-fidelity and Arch design Wiki page is already created

Info on low-fidelity and arch design (may not be the best sources, find your own if necessary)
* [ARCH](https://www.tutorialspoint.com/software_architecture_design/introduction.htm)
* [LOW-FI](https://www.visily.ai/blog/what-is-low-fidelity-wireframe/)

Look into using a drawing program to create these designs
* [FIGMA](https://www.figma.com/)

Look at Team 3 [Wiki](https://github.com/DrAlzahraniProjects/csusb_fall2024_cse6550_team3/wiki/System-design-(low‐fidelity)-and-architecture-diagrams)

**WIKI MUST BE DETAILED AND PROFESSIONAL AS PER DR. ALZAHRANI. IF YOU NEED HELP PLEASE ASK**

**Comment by 008445808** [comment]
task was completed and uploaded the all the files that are required

**Comment by itsnotmik** [comment]
# 10/3 Update
* Content looks good
* The current `Architecture Design` needs to be renamed to `Infrastructure Design`
* New infrastructure needs to be created
    * Needs to be like [Team 3](https://github.com/DrAlzahraniProjects/csusb_fall2024_cse6550_team3/wiki/System-design-(low‐fidelity)-and-Architecture-Diagram) and [Team 4](https://github.com/DrAlzahraniProjects/csusb_fall2024_cse6550_team4/wiki/Architecture-diagram)
    * Must be reformatted into this [layout](https://www.figma.com/design/dd9cr830l58kiP4Gw3Jbep/Untitled?node-id=0-1&t=u1YgInWO3ZAyCgkT-1)
        * **LAYOUT MUST BE IN THIS FORMAT**! Reference Team 3 and Team 4 for the content, then reformat into this layout

**Comment by Jagadeesh-ajjada** [comment]
Updated Architecture Diagram check and lemme know are there any changes required.

**Comment by itsnotmik** [comment]
Looks solid for now. We can make changes later to match the system as we go!

**Comment by itsnotmik** [comment]
From Dr. Alzahrani's comments in class:

* We need a Frontend Backend layout, instead of a Presentation, Business, and Database layer
* Text needs to be larger and more readable
* Need more colors and images.

Refer to [Team 4](https://github.com/DrAlzahraniProjects/csusb_fall2024_cse6550_team4/wiki/Low-Fidelity-&-Architecture-diagram). Though I feel that we shouldn't go as simple as theirs

**Comment by 008445808** [comment]
updated the images of the architecture .let me know for any updates

**Comment by ACraig7** [comment]
Looks good. Probably should add Milvus to the datatbase

**Comment by 008445808** [comment]
the  changes were updated please review the changes
