### ISSUE TITLE
Dockerfile no longer builds

### ISSUE THREAD

**Issue by Boganabi** [DrAlzahraniProjects/csusb_fall2024_cse6550_team1#87]
Hello all,
Upon building the app today, I encountered this error message on both my Windows 11 system and Linux subsystem:
![image](https://github.com/user-attachments/assets/463eb981-9348-43fd-8d61-6ce0bdd8975e)
The error points to where we install Miniforge on line 22 in the Dockerfile, and claims that Mambaforge is deprecated. 

Is this an error on my end or something that broke since last week?
No worries if we cannot fix this before class, I can revert my local git to when it was working last week.

**Comment by itsnotmik** [comment]
Im working on a fix now. Gonna convert to miniforge installation

Even though this shouldn't have been a problem because Mambaforge works until January of 2025. And I tested the last merge and it worked. But I didn't rebuild it, it used cache so maybe with no cache it would fail

**Comment by Boganabi** [comment]
Tried with `--no-cache` and without that tag, both result in the same error. Running the old image still works, so my guess is that they removed support in the last few days or so.

**Comment by Boganabi** [comment]
According to this https://conda-forge.org/news/2024/07/29/sunsetting-mambaforge/ they started brownouts on certain installers literally today. Could not have been worse timing lmao

**Comment by Boganabi** [comment]
Fixed with recent pull
