### ISSUE TITLE
RAG Chatbot Review

### ISSUE THREAD

**Issue by itsnotmik** [DrAlzahraniProjects/csusb_fall2024_cse6550_team1#92]
@acraig07 @smrchanda877 @Jagadeesh-ajjada 

I have pushed a basic RAG setup onto the branch `milvus-langchain-setup`

Please give it a test when you have a chance

Here are the details:
* Using Cohere model instead of MistralAI
    * MistralAI did not work with web loaded pages (Illegal header b'Bearer ' error)
        * Could not find a solution online so I used a different model
    * You will need a Cohere API Trial Key which can be obtained [here](https://dashboard.cohere.com/api-keys)
        * The key should be place in your `.env` file inside the main directory in this format `COHERE_API_KEY='<key>'`
* Only contains the main page of ITS found [here](https://www.csusb.edu/its/)
    * Ask it any question related to that page and see how it answers
        * My basic testing had it answers perfectly accurate
* The model is **SLOW**
    * This is because we are creating the vector store every question we ask + COHERE trial may be slowing us down
         * Will be fixed later but for initial testing and feedback it is fine enough
* Cohere model is **NOT** the long term model to replace Mistral
    * Cohere trail keys are both rate limited and capped per month as found [here](https://docs.cohere.com/v2/docs/rate-limits)
        * Any model should be drag and drop as long as it exists within langchain models found [here](https://python.langchain.com/docs/integrations/chat/)

**Comment by itsnotmik** [comment]
If you have any questions, concerns or suggestions please let me know

**Comment by ACraig7** [comment]
Maybe I am doing something wrong, but

- Got the API key from Cohere
- Put it in a `.env` file
- Build the image and ran it
- When saying "hello" or asking it a question based on the IT page it does this:
![image](https://github.com/user-attachments/assets/c0426361-1766-4edf-b3f6-b23d6d83df2e)

This is the error and traceback: 
```
ConnectionConfigException: <ConnectionConfigException: (code=1, message=Open local milvus failed, dir: milvus is not exists)>
Traceback:

File "/opt/miniforge/envs/team1_env/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
File "/opt/miniforge/envs/team1_env/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
File "/app/app.py", line 134, in <module>
    main()
File "/app/app.py", line 111, in main
    answer = RAG_answer(prompt)
File "/app/RAG.py", line 28, in RAG_answer
    vector_store = initialize_milvus()
File "/app/RAG.py", line 75, in initialize_milvus
    vector_store = create_vector_store(docs, embeddings, URI)
File "/app/RAG.py", line 97, in create_vector_store
    vector_store = Milvus.from_documents(
File "/opt/miniforge/envs/team1_env/lib/python3.10/site-packages/langchain_core/vectorstores/base.py", line 830, in from_documents
    return cls.from_texts(texts, embedding, metadatas=metadatas, **kwargs)
File "/opt/miniforge/envs/team1_env/lib/python3.10/site-packages/langchain_milvus/vectorstores/milvus.py", line 1241, in from_texts
    vector_db = cls(
File "/opt/miniforge/envs/team1_env/lib/python3.10/site-packages/langchain_milvus/vectorstores/milvus.py", line 326, in __init__
    self.alias = self._create_connection_alias(connection_args)
File "/opt/miniforge/envs/team1_env/lib/python3.10/site-packages/langchain_milvus/vectorstores/milvus.py", line 410, in _create_connection_alias
    raise e
File "/opt/miniforge/envs/team1_env/lib/python3.10/site-packages/langchain_milvus/vectorstores/milvus.py", line 405, in _create_connection_alias
    connections.connect(alias=alias, **connection_args)
File "/opt/miniforge/envs/team1_env/lib/python3.10/site-packages/pymilvus/orm/connections.py", line 375, in connect
    raise ConnectionConfigException( 

```

**Comment by itsnotmik** [comment]
I just forgot to create the directory in the `RAG.py` file. I had the folder locally and didn't have to create it.

`milvus-langchain-setup` has been updated to mkdirs for milvus setup

Can you give it another try?

**Comment by ACraig7** [comment]
It is working just as you described, it takes around 5-10 seconds to answer a question. I did ask it "What is the mission?" and it could not answer, which is the first thing on the IT site. Here is a screenshot: 
![image](https://github.com/user-attachments/assets/de01ef81-5e98-4cfe-97a3-1a9d8d4eb24d)

**Comment by itsnotmik** [comment]
The .env is ignored now because we are in a public repo and if we all use one key it will cause us testing problems. We can brainstorm a solution in the future though

Also I am unsure why it can not answer `What is the mission?` but it can answer `What is the CSUSB mission?`

Could be an issue with the Cohere model itself. Maybe a different model will be able to handle the information better. Would be useful to test/research

Answers available in the following screenshots:
![image](https://github.com/user-attachments/assets/904a5f62-287c-4a88-9b2f-93a3a28658c8)
![image](https://github.com/user-attachments/assets/6356db04-6062-47a0-86de-b849cb966b29)

Otherwise, any suggestions/ideas?

**Comment by ACraig7** [comment]
Yeah, I get why we ignore the .env, I just don't know how he wants us to handle that in the future. I think you are right that it is an issue with the model on why it cant answer "What is the mission?" Also, for mistral not being able to load webpages, maybe we have to download the data into some format that Mistral could rag. Well, we may not even use Mistral in the end cause of API limits. I have done a good amount of research and cant find out limits of when the free version of Mistral runs out.

**Comment by itsnotmik** [comment]
I will load some other models in and see if it has better capabilities. I am unsure about the long term of what the professor wants but for now it's probably best to get it running even if it's limited. Ill provide further update later tonight

In regards to loading the data separately, im sure it may be possible, im just not sure if its worth working towards if other models work with the webpage data.

**Comment by smrchanda877** [comment]
I've run this in local and yeah, I am also getting very slow responses.

- I've made some changes in UI. like adding a loading icon till the response is loaded. 
- I'm currently looking for a way to not create a vector_store for every message. I've tried some stuff, like calling the initialize function in the start of app.py while creating session_state.messages. It works kinda, but it takes a lot of time for the vector_store to get created and it still takes 3-5 seconds for every response on top of the initital loading time. I'll update you guys if I find anything.

For now, I'll create a PR to milvus-langchain-setup for the loading icon changes. @itsnotmik Please review and merge.

**Comment by smrchanda877** [comment]
- I've created a PR from `milvus-langchain-setup` to `main` #95
- @itsnotmik @ACraig7 @Jagadeesh-ajjada Please review and merge

**Comment by vamsikrishnabandaru3** [comment]
it is no longer providing responses and instead returns a 401 Unauthorized error

<img width="1424" alt="Screenshot 2024-10-06 at 9 14 33 PM" src="https://github.com/user-attachments/assets/02331072-eb94-4442-8c65-9f3a038225d2">

**Comment by itsnotmik** [comment]
@vamsikrishnabandaru3 Sorry the model was switched back to MistralAI. 

You will have to create a `.env` file with the line `MISTRAL_API_KEY='<api_key>'`. The api key can be obtained from [here](https://console.mistral.ai/api-keys/)

**Comment by itsnotmik** [comment]
@smrchanda877 @ACraig7 

I was testing RecursiveUrlLoader for depth 2. It loads 90 pages.

This increase the ~2 minute load time to much much longer. This includes the embedding + webloading

We should look into either:
* Manually processing the pages into files and loading them
    * Would still require us to embed them once the docker starts
    * Lots of manual work to get the files converted correctly
* Running RecursiveUrlLoader or WebBaseLoader and downloading the `.db` file it creates
    * Using a prebuilt `.db` wouldn't require embedding on each run
    * Using RecursiveUrlLoader doesn't have BeautifulSoup parsing (unsure how this will affect performance)
    
Either way generating the files and embedding during runtime is probably not possible.

Let me know what you guys feel on the matter

**Comment by ACraig7** [comment]
@itsnotmik either one sounds good and they both have their ups and downs. We should test both if we have the time to find the fastest but before we do that we should try and get a sitemap so we can confirm that we have all of the correct pages and that the recursive loader is grabbing all of them correctly.
