### ISSUE TITLE
Docker Scout Documentation

### ISSUE THREAD

**Issue by itsnotmik** [DrAlzahraniProjects/csusb_fall2024_cse6550_team1#99]
# 10/3 Update
* Content looks good
* Please include 10 **MEANINGFUL** screenshots with descriptions throughout the documentation

# Original Task 
### Scout Wiki page is already created

Include complete documentation including
* Installation
* Configuration
* Implementation
* Usage (to produce results/reports)
* Troubleshooting (to resolve errors)

Make sure to use 2-panel design: one for content and one for navigation like [HERE](https://github.com/Netflix/Hystrix/wiki)

**WIKI MUST BE DETAILED AND PROFESSONAL AS PER DR. ALZAHRANI. IF YOU NEED HELP PLEASE ASK FOR HELP**

**Comment by Adenkri45** [comment]
Sure Michael will work on that and thanks for reviewing the content.

**Comment by itsnotmik** [comment]
Please include how to use docker scout on our project as well

**Comment by ACraig7** [comment]
I forget who asked about running Docker Scout in the meeting today but it can not analyze the image from the docker desktop app for whatever reason. Although, it does seem to work through the CLI commands found [here](https://docs.docker.com/scout/explore/analysis/#cli). Try the commands there and see what happens.

**Comment by Adenkri45** [comment]
> I forget who asked about running Docker Scout in the meeting today but it can not analyze the image from the docker desktop app for whatever reason. Although, it does seem to work through the CLI commands found [here](https://docs.docker.com/scout/explore/analysis/#cli). Try the commands there and see what happens.

Hey Andrew.! that was me btw. Thanks for the reply i will got through it and update you over here if it works or not.
